#import './UserFragment.gql'
#import './UserFollowingFragment.gql'
#import './UserFollowersFragment.gql'
mutation updateUser($id: ID!, $follow: ID!) {
  updateUser(
    data: { following: { connect: { id: $follow } } }
    where: { id: $id }
  ) {
    ...User
    ...Following
    ...Followers
  }
  dummy: updateUser(data: { dummy: "dummy" }, where: { id: $follow }) {
    id
  }
}
